[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
marinade_idl = "CHi4sCSpmcDVVzhefrWe2MJrERACUNUWC43eEXpPsnPC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/davirian/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
